//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiNew.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiNew.App_GlobalResources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Resim Yoluna Erişilemiyor!.
        /// </summary>
        internal static string AccessImagePathFail {
            get {
                return ResourceManager.GetString("AccessImagePathFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Resim Yoluna Erişilemiyor. Hata: {0}.
        /// </summary>
        internal static string AccessImagePathFailFormatted {
            get {
                return ResourceManager.GetString("AccessImagePathFailFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Resim Yoluna Erişim Sağlandı..
        /// </summary>
        internal static string AccessImagePathOk {
            get {
                return ResourceManager.GetString("AccessImagePathOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler alınırken sunucu hatası: {0}.
        /// </summary>
        internal static string BilgilerAlinirkenSunucuHata {
            get {
                return ResourceManager.GetString("BilgilerAlinirkenSunucuHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Veritabanına bağlantı sağlanamadı!.
        /// </summary>
        internal static string DbConnectionFail {
            get {
                return ResourceManager.GetString("DbConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Veritabanına Bağlantı Başarılı.
        /// </summary>
        internal static string DbConnectionSuccessful {
            get {
                return ResourceManager.GetString("DbConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata: {0}.
        /// </summary>
        internal static string errorFormatted {
            get {
                return ResourceManager.GetString("errorFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma listesi alınırken sunucu hatası: {0}.
        /// </summary>
        internal static string FirmaListError {
            get {
                return ResourceManager.GetString("FirmaListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma tipleri alınırken sunucu hatası: {0}.
        /// </summary>
        internal static string GetCalismaAyarListError {
            get {
                return ResourceManager.GetString("GetCalismaAyarListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma listesi alınırken sunucu hatası: {0}.
        /// </summary>
        internal static string GetCalismaListError {
            get {
                return ResourceManager.GetString("GetCalismaListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator listesi alınırken sunucu hatası: {0}.
        /// </summary>
        internal static string GetCalismaOperatorListError {
            get {
                return ResourceManager.GetString("GetCalismaOperatorListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orjin Yazılım Mobil Web Servis.
        /// </summary>
        internal static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri Mevcut!.
        /// </summary>
        internal static string IsemriMevcut {
            get {
                return ResourceManager.GetString("IsemriMevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        internal static string KayitBulunamadi {
            get {
                return ResourceManager.GetString("KayitBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt işlemi başarısız oldu!.
        /// </summary>
        internal static string KayitEdilemedi {
            get {
                return ResourceManager.GetString("KayitEdilemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kodlu iş talebi oluşturuldu..
        /// </summary>
        internal static string KodluIsTalebiOlusturuldu {
            get {
                return ResourceManager.GetString("KodluIsTalebiOlusturuldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod oluşturulurken sunucu hatası: {0}.
        /// </summary>
        internal static string KodOlusturError {
            get {
                return ResourceManager.GetString("KodOlusturError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı güncellenirken sunucu hatası: {0}.
        /// </summary>
        internal static string MakineCalismaKartGuncelleErr {
            get {
                return ResourceManager.GetString("MakineCalismaKartGuncelleErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı başarılı bir şekilde güncellendi.
        /// </summary>
        internal static string MakineCalismaKartGuncelleOk {
            get {
                return ResourceManager.GetString("MakineCalismaKartGuncelleOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı kaydedilirken sunucu hatası: {0}.
        /// </summary>
        internal static string MakineCalismaKartKayitErr {
            get {
                return ResourceManager.GetString("MakineCalismaKartKayitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı başarılı bir şekilde kaydedildi..
        /// </summary>
        internal static string MakineCalismaKartKayitOk {
            get {
                return ResourceManager.GetString("MakineCalismaKartKayitOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı güncellenemedi!\nKayıtta değişiklik algılanmadı!.
        /// </summary>
        internal static string MknCalismaKartKayitDegisiklikYok {
            get {
                return ResourceManager.GetString("MknCalismaKartKayitDegisiklikYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı güncellenemedi!\nBöyle bir kayıt yok!.
        /// </summary>
        internal static string MknCalismaKartKayitKayitYok {
            get {
                return ResourceManager.GetString("MknCalismaKartKayitKayitYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör güncellenirken sunucu hatası: {0}.
        /// </summary>
        internal static string MknCalismaOperatorGuncelleHata {
            get {
                return ResourceManager.GetString("MknCalismaOperatorGuncelleHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör başarılı bir şekilde güncellendi.
        /// </summary>
        internal static string MknCalismaOperatorGuncelleOk {
            get {
                return ResourceManager.GetString("MknCalismaOperatorGuncelleOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör kaydedilirken sunucu hatası: {0}.
        /// </summary>
        internal static string MknCalismaOperatorKayitHata {
            get {
                return ResourceManager.GetString("MknCalismaOperatorKayitHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör başarılı bir şekilde kaydedildi..
        /// </summary>
        internal static string MknCalismaOperatorKayitOk {
            get {
                return ResourceManager.GetString("MknCalismaOperatorKayitOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı silinemedi!.
        /// </summary>
        internal static string MknCalismaSilHata {
            get {
                return ResourceManager.GetString("MknCalismaSilHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı silinemedi!\nBöyle bir kayıt yok!.
        /// </summary>
        internal static string MknCalismaSilKayitYok {
            get {
                return ResourceManager.GetString("MknCalismaSilKayitYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı başarıyla silindi.
        /// </summary>
        internal static string MknCalismaSilOk {
            get {
                return ResourceManager.GetString("MknCalismaSilOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine çalışma kartı silinirken sunucu hatası: {0}.
        /// </summary>
        internal static string MknCalismaSilSunucuHata {
            get {
                return ResourceManager.GetString("MknCalismaSilSunucuHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör silinemedi!.
        /// </summary>
        internal static string MknOperatorSilHata {
            get {
                return ResourceManager.GetString("MknOperatorSilHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör silinemedi! Böyle bir kayıt yok!.
        /// </summary>
        internal static string MknOperatorSilKayitYok {
            get {
                return ResourceManager.GetString("MknOperatorSilKayitYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör başarılı bir şekilde silindi.
        /// </summary>
        internal static string MknOperatorSilOk {
            get {
                return ResourceManager.GetString("MknOperatorSilOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör silinirken sunucu hatası: {0}.
        /// </summary>
        internal static string MknOperatorSilSunucuHata {
            get {
                return ResourceManager.GetString("MknOperatorSilSunucuHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör güncellenmedi!\nKayıtta değişiklik algılanmadı!.
        /// </summary>
        internal static string MknOprGuncelleDegYokHata {
            get {
                return ResourceManager.GetString("MknOprGuncelleDegYokHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör güncellenemedi!\nBöyle bir kayıtyok!.
        /// </summary>
        internal static string MknOprGuncelleKayitYokHata {
            get {
                return ResourceManager.GetString("MknOprGuncelleKayitYokHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı iş emrine atandınız..
        /// </summary>
        internal static string NoluIsemrineAtandiniz {
            get {
                return ResourceManager.GetString("NoluIsemrineAtandiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı iş emri oluşturuldu..
        /// </summary>
        internal static string NoluIsemriOlusturuldu {
            get {
                return ResourceManager.GetString("NoluIsemriOlusturuldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı malzeme talebi oluşturuldu..
        /// </summary>
        internal static string NoluMalzemeTalebiOlusturuldu {
            get {
                return ResourceManager.GetString("NoluMalzemeTalebiOlusturuldu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel bağlantısı bulunmadığı için profil fotoğrafı kaydedilmedi!.
        /// </summary>
        internal static string PersonelBilgiYokKayitEdilemedi {
            get {
                return ResourceManager.GetString("PersonelBilgiYokKayitEdilemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim bilgisi kaydedilirken hata oluştu! Hata : {0}.
        /// </summary>
        internal static string ResimKayitHata {
            get {
                return ResourceManager.GetString("ResimKayitHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni İş Emri!.
        /// </summary>
        internal static string YeniIsEmri {
            get {
                return ResourceManager.GetString("YeniIsEmri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni İş Talebi!.
        /// </summary>
        internal static string YeniIsTalebi {
            get {
                return ResourceManager.GetString("YeniIsTalebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Malzeme Talebi!.
        /// </summary>
        internal static string YeniMalzemeTalebi {
            get {
                return ResourceManager.GetString("YeniMalzemeTalebi", resourceCulture);
            }
        }
    }
}
